source 'https://rubygems.org'

ruby '~> 2.5.0'

gem 'rack-ssl-enforcer'
gem 'dotenv'
gem 'foreman'
gem 'json'
gem 'octokit'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-strong-params', :require => 'sinatra/strong-params'
gem 'sinatra_auth_github'
