#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'assets/components/**/*.s+(a|c)ss'
  ignore:
    - 'assets/sass/vendor/**/*.*'
    - 'assets/components/design/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - respond-to
        - link
        - link-hover
        - placeholder

  no-warn: 0
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  # variable-for-property:
  #   - 2
  #   -
  #     properties:
  #       - content
