title: "Content Page Layout"
status: "ready"

context:
  preview:
    noPad: true
  # Hero Context
  hero:
    heading: Content Page
    breadcrumbs: true
    sidenav: true

  # Hero Lede
  lede:
    message: 'Some introductory text lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vulputate magna velit. Vestibulum fermentum fermentum libero. Vestibulum dui dui, pulvinar bibendum nulla eget, lacinia fermentum lorem.'

  # Nav context
  nav:
    modifier: m-nav--large
    items:
    -
      title: Getting Started
    -
      title: Creating open standards
    -
      title: Find existing standards
    -
      title: How to use this guide
    -
      title: Introduction

  # The nav metatitle
  metatitle:
    message: Contents
