backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: "jekyll/uploads"
public_folder: "/uploads"

collections:
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Main nav"
        name: "main_nav"
        file: "_data/main_nav.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Url
                name: url
                widget: string

      - label: "Top auxillary nav"
        name: "top_aux_nav"
        file: "_data/top_aux_nav.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Url
                name: url
                widget: string

      - label: "Footer auxillary nav"
        name: "footer_aux_nav"
        file: "_data/footer_aux_nav.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
                - label: Path
                  name: path
                  widget: string

      - label: "Snippets"
        name: "snippets"
        file: "_data/snippets.yml"
        fields:
          - label: "Intro sentence"
            name: "intro_sentence"
            widget: "text"
